### ISSUE TITLE
Error when Youtify open in multiple tabs

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#141]
When I open Youtify in multiple tabs (happens often when I get links from friends I often get this annoying error: »Your account has been used somewhere else. Please reload the page.«

Can that be handled and solved in the background? This is not something people should need to do.

**Comment by auroranockert** [comment]
Yes, extremely important. Especially when you're logged in on another device that is somewhere else.

**Comment by kallux** [comment]
It would seem that /ping started to generate device ids. That is why conflicts are happening more often now. 

The "right" solution which is only to reload parts of playlists that has been changed (tracks), is hard to do since all tracks are stored in JSON at the backend. 

What we could do is that we update the playlists that has been changed if the client get a reload request from the server on save. But it's still tricky and can lead to memory leaks.

**Comment by kallux** [comment]
OK, so I found out why the device id is different even if you just entered the page. Because we have a "catch all" in the bottom of app.yaml, requests like /favicon.ico also generates a new device id. This seems to happen also if you enter /ping for some strange reason. The solution is to only redirect / to main and everything else to a 404. This will also reduce load and lower server costs. I'll implement this change and push it tonight.

Edit: On second thought, this is a bad idea since we added www.youtify.com/username so I only created a list of blocked URLs in main.py
