### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#179]
Since a while I have some thoughts on how to design a better music player. Today I analyzed some popular apps similar to Youtify (Spotify, rdio, Google Play Music, Youtube, Vimeo, Grooveshark, Musicplayr, iTunes, Rhythmbox, Tomahawk, …), thought about what interface elements are needed and made some mockups.

This is only a first batch of redesign, focusing on the main static parts being the player (currently bottom bar and video) and the top bar.

First an overview:
![overview](http://i.imgur.com/FQIfJ.jpg)
The top bar has a logo, search bar, controls for shuffle and volume as well as a user menu.
The always visible song infos are video/cover with time bar on the bottom, as well as the controls Play, Previous and Next.

Let’s get into detail: song player
![player](http://i.imgur.com/i5IFP.jpg)
The additional stuff for the song are the song title (bold), artist name, and a fullscreen button. They appear when hovered, when the song is changed and when the Youtify tab gets focus. In the two latter cases, they fade out after a few seconds to not obstruct the video.
Next to the song title and artist name there should be an arrow or similar, which on click shows the popover with further info (uploader, Flattr etc) as now already. Should also show when just clicking the song title or artist name itself.
On hover it is also possible to use the time bar, which is unobtrusive underneath the video and shows the current time in a small popover (see Vimeo). A wide time bar which takes nearly the entire width is not needed.

![volume](http://i.imgur.com/5vLCD.jpg)
The controls for volume and shuffle are in the top bar because they are only rarely needed. They do not belong to the song itself but are rather global settings. Clicking the volume icon reveals a small popover.

![usermenu](http://i.imgur.com/LJHUu.jpg)
Instead of having the top right crowded with very rarely needed settings (as well as a big destructive log out button) this will be consolidated into one user menu. It has entries for Profile, Settings, About and Sign out. Profile will open the user profile, Settings and About will change the popover to show the respective menu (much like now) and Sign Out will simply sign out.

That’s it for now, let me know what you think.

**Comment by jancborchardt** [comment]
An additional thought on the player controls – we could even go so far as to _not_ have the Play, Previous and Next controls show at all times. Rather have them also overlay the video and only be visible on hover, on song change, and when you open the app until you play a video (and when you paused the current song).

**Comment by kallux** [comment]
Right now we're redesigning the page in the branch 320design. This is not something we wanted to do at this very moment since there are other areas we _really_ need to focus on. Unfortunately YouTube has changed their minimum required player size so our old design doesn't work anymore. If we could, we would only change the left column to the minimum width, but that looked like crap. So we decided that a somewhat larger effort had to be done. The new design is a standard 3 colors design, and we are mimicking a lot on what the other players are doing and trying to keep as much existing as possible. 

Jan: Your post has helped with lots of ideas here and even though we're not going to make massive changes in this design sprint, I think this issue should stay open. Ideas and discussions could take place here until we feel ready to make a completely new and innovative interface that kicks ass!
