### ISSUE TITLE
context menu partly duplicates interface

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#180]
»Play« duplicates the play button to the left of every song, and »View on Youtube« (or SoundCloud/Official.fm) should just be linked to the logo which is shown on the right.

Then those two entries should be removed from the context menu.

**Comment by pthulin** [comment]
I want to continue having these alternatives in the context menu as it seems to be the standard (Spotify and iTunes has "Play" i there).

**Comment by jancborchardt** [comment]
Regardless of what they have in there, it simply does not make sense to clutter up the menu with points which are more easily reachable. Because simply when you want to reach the additional functions, they should be easily findable and clickable and not buried under duplicates of already more easily accessible functions.

**Comment by kallux** [comment]
I really like a clean interface where functionality isn't cluttered, duplicated and spread all over the screen, but it also has to be logical for the user where to find the functionality that they're looking for. Since this is a music player, I don't think we should be restrictive with the play button. 

Users come from different experience. For example the windows people are used to right click on everything and the default double click action is always expected to be the first item in the context menu. 

Also I personally think that the context menu is a great dictionary or help. I expect to find every action that I can do with an item in the context menu and maybe also discover actions that I didn't know was possible. If I then find a function/action that I use a lot, I don't mind clicking a shortcut or something else if it's faster than the context menu. But the point is that no matter what program I use, I expect _all_ actions to be on the context menu.

I like the idea of shortcuts but I think we should back that up with both data and make the shortcuts simple and understandable. For example I think we should find out what context menu item the users use the most, and from there decide what shortcuts we should place on the track. 

With all this being said, I'm going to put the "Watch on..." menu item back to the context menu and if we need a shortcut, we should think of a better one than using the "type" icon, since this so far has only been a label. We need an icon to which the user understands the action before the click it. Right now, you have no idea what will happen if you click the type icon (or at least it's far fetched).

**Comment by jancborchardt** [comment]
Even though this is a music player, we don’t need to put play buttons all over the place. I don’t have any data on Youtify specifically at the moment, but from a lot of design & usability testing experience I can generally say that it’s better to have a function only in one place where it makes sense. Every music player has very visibly to the left of the list item.

So then when you actually want to use the right-click menu, that menu should not distract you with functions which are already very visibly available, just for the sake of being a collection or sitemap of all the functions you can perform on that element. That’s not how people think – filled up context menus are the bane of applications.

As with the »Watch on …« link – I’d say it’s pretty obvious to click the Youtube or SoundCloud icon to get to the song there. And even if it’s not, it’s not super important that people understand that action on first glance or are presented with it every time they open the context menu. Youtify already plays the music and shows the video. If they really want to view it on the source, it’s pretty easy to find out.

Interface design is not about showing people all the things they can do whenever it’s possible. But rather to only show people relevant actions when they probably need it. The general goal should be to get rid of the right-click menu completely (or as much as possible) and rather transform it into contextually relevant actions. For instance, right-clicking an empty playlist suggests »Remove duplicates« and other things which are not relevant at that point.

What do you think?

**Comment by kallux** [comment]
First of all, the context menu is a power feature. I dare guess that no one uses it in 90% of their interaction with an item. But when you look for that extra function that you just don't find at the first glimpse, then you right-click. Or at least I do.

On the OS that I'm on and in the applications that I use, the first context menu item is always the action that happens if you double click on an item. That is one of the main reasons why play should be the first option in the context menu. Consistency is key to usability. 

I know lots of people with macs never use the context menu (and they couldn't for many years with only one mouse button available), while the windows users used it for everything. But I think that we have finally after many years come to some sort of balance between the context menu and clearly visible shortcuts/buttons.

> The general goal should be to get rid of the right-click menu completely (or as much as possible) and rather transform it into contextually relevant actions.

I kind of agree with this. But the goal should not be to get rid of the context menu, but to make sure that no one feel the need to use it in normal use. (Just like _nobody_ uses the help in an application until they come across something that they can't figure out)

I've uninstalled many programs in my days, just because options/buttons just appeared/disappeared and I couldn't find the action that I was looking for. If users become frustrated and leave because we replaced a context menu item with a 16x16 icon and they couldn't find it. Then we failed and most likely lost a user.

The baseline is that I'd rather have a cluttered and ugly interface where the users don't have to spend time searching for functions, than a clean good looking interface where users become frustrated. `Usability >= Design`

**To the normal user, the results of this discussion probably won't have much (if any) impact. Both points of views are reasonable and in the end it's more of a personal preference.**

**Comment by jancborchardt** [comment]
First of all, I highly disagree with your concluding sentence. Application design for the most part is definitely not personal preference. If I didn’t think it would have an impact to users, I wouldn’t have brought it up.

Also what you describe as consistency is just doing it like desktop apps, for the sake of it. There is no reason why the first item of the right click menu is the same that happens when you double-click it.

Especially the right-click menu of Youtify is _not_, as you say, a power feature. The items are essential. Let’s look at each one:
- Play: Duplicates the big giant play button. No reason that this is here, it just obscures the other items.
- Queue: Some players either have a queue button next to the play button, or they queue automatically when currently a song plays, to not interrupt the current song.
- Add to playlist: This is fully done by drag & drop and there really should be no weird backup solution for this. Instead of making it seem like you need to use the ugly right-click and dropdown-choose playlist solution, it should be made easier to know that drag & drop can be used for this.
- Share: Awesome, but too hidden.

Good design leaves a single item, Share, which can then be in the space where the menu dropdown is. And then each action is more easily findable because it was designed well.

You say you uninstalled programs because you couldn’t find buttons. Just randomly hiding functions is exactly not what I’m saying. Then again, a cluttered interface is exactly what people have problems with and will not find the function they need in. See Microsoft’s ribbon. Or every context menu ever. »Findability« is a concept which can lead to very misguided results, as is »Consistency«.

Of course, getting rid of the context menu is only the means to the end – of having an easier-to-use app with less hidden stuff and more contextual controls. Let’s work on a clean and good looking interface where users don’t have to spend time searching for functions because everything is contextual.

Usability is not >= Design, they interoperate. If we focus on one way to do it for every specific action, we can polish that flow way better than having one or several alternatives which make the whole app seem less great.

**Comment by pthulin** [comment]
Jan, we're not doing it like desktop apps just "for the sake of it", we're doing it because we're targeting users coming from those apps and we want to make their transition as easy as possible. When looking at iTunes and Spotify, they both have context menus and they both have these alternatives in there.

The second reason we have these alternatives in a context menu is due to the smaller playlist view where there's not as much space.

**Comment by jancborchardt** [comment]
I know that is the reason, I’m just saying it’s a bit misguided, using »Consistency« as the argument. If it just looks the same as all the other apps, why would I use Youtify? If on the other hand, it has these little details which make it easier to use, it reduces the time I fiddle with the interface and increases the time I actually listen to music. iTunes and Spotify duplicating the play button in the right-click menu is no reason to also do it. Small but nice improvements over other apps is what people enjoy.

If the playlist view is too small to show all the actions, then the solution is to simply show a dropdown just there. But not to also show it everywhere else. That’s what I mean with contextual controls.

**Comment by jancborchardt** [comment]
Case in point: We didn’t design the [ownCloud](http://ownCloud.org) Files app like any other file manager, because they were all completely, mostly or partly badly designed. Now you clearly see what you can act upon and what happens, and it has been proven mostly good design through usability tests.

Better design makes the transition easier for people because they see the value in moving. As opposed to when it looks mostly like the thing they use currently, where it is not apparent why they should switch at all.

**Comment by pthulin** [comment]
This might sound boring, but Youtify, at its current stage, is not about making a better UI than the other music players. Rather, we focus our innovation on other areas such as how artists should get paid. The goal of the UI is to just be what people expect from a music player, and mimicking desktop apps and their paradigms is the direction we have chosen and is what we are sticking with for now.

I know me and @kallux have to become better at communicating our ideas and broader goals for the project (there are still big parts of the Youtify plan that we haven't even started with yet).

**Comment by jancborchardt** [comment]
To quote the great Jef Raskin: »As far as the customer is concerned, the interface is the product.«

There is no reason that the interface can’t be better as well, improving alongside the underlying technology. In fact it should be, for aforementioned reasons. You can have the most awesome technology and system for artist payment, but if people are faced with a cumbersome interface, it will not get used.
I’m ready to contribute and will do the changes I suggest myself (as far as I am able to), but I don’t just want to jump in and change code without having talked about it here first. It’s an open-source project, so I’d really love to help with the design & usability.

**Comment by pthulin** [comment]
I agree 100% that UI and design are important but what I'm saying is that being on par with Spotify and iTunes is enough for what we are aiming for right now. I'm saying this because as I said, the UI is not our selling point at this stage and as work is done almost entirely by me and @kallux, time is limited. Of course, if we can add clear wins over the other players's UI and if they come free to us as of your contributions, we should. However I don't consider this a clear win as our current strategy is that of mimicking paradigms from desktop applications.

Really, what I'd like to see is that you put together your ideas (this and #112) into a more general proposal (I think a Milestone here on GitHub would be best) for making the interface adjusted to web conventions instead of desktop conventions. This is something that we should look into in the future as the world is moving away from desktop applications and more into web and mobile.
